PROG := synthctrl
SRCS := synthctrl.cpp io.cpp
OBJS := $(SRCS:%.cpp=%.o)
DEPS := $(SRCS:%.cpp=%.d)
INCL := -I picojson -I rtmidi-2.1.0
LIBS := -framework CoreAudio -framework CoreFoundation -framework CoreAudio -lm rtmidi-2.1.0/librtmidi.2.1.0.dylib
CC := g++

all: $(PROG)

-include $(DEPS)

$(PROG): $(OBJS)
	$(CC) $(LIBS) -o $@ $^

%.o: %.cpp
	$(CC) -c -MMD -MP $< $(INCL) 

clean:
	rm -f $(PROG) $(OBJS) $(DEPS)


